@startuml
/' --- Оформление --- '/
skinparam BackgroundColor #FFFFFF
skinparam ArrowColor #000000
'skinparam linetype ortho

skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor Red
skinparam titleBackgroundColor Cyan

skinparam ActorBorderColor #000000
skinparam ActorBackgroundColor #FFFFFF
skinparam UsecaseBorderColor #000000
skinparam UsecaseBackgroundColor #FFFFFF

(Поиск) as (Поиск)
(Просмотр \n списка объектов) as (Просмотр_списка_объектов)
    (Просмотр \n объекта) as (Просмотр_объекта)
        (Добавление в \n свои объекты) as (Добавление_в_свои_объекты)
        (Удаление из \n своих объектов) as (Удаление_из_своих_объектов)
        (Добавление \n в закладки) as (Добавление_в_закладки)
        (Удаление \n из закладок) as (Удаление_из_закладок)
(Редактирование \n списка объектов) as (Редактирование_списка_объектов)
    (Добавление \n объекта) as (Добавление_объекта)
    (Редактирование \n объекта) as (Редактирование_объекта)
        (Редактирование \n данных объекта) as (Редактирование_данных_объекта)
        (Загрузка \n медиафайла) as (Загрузка_медиафайла)
    (Удаление \n объекта) as (Удаление_объекта)
(Просмотр \n своих объектов) as (Просмотр_своих_объектов)

Актор --> (Поиск)
Актор --> (Просмотр_своих_объектов)

(Поиск) o-- (Просмотр_списка_объектов)
(Просмотр_списка_объектов) o-- (Просмотр_объекта)
(Просмотр_списка_объектов) o-- (Добавление_в_свои_объекты)
(Просмотр_списка_объектов) o-- (Удаление_из_своих_объектов)
(Просмотр_списка_объектов) o-- (Добавление_в_закладки)
(Просмотр_списка_объектов) o-- (Удаление_из_закладок)
(Просмотр_объекта) o-- (Добавление_в_свои_объекты)
(Просмотр_объекта) o-- (Удаление_из_своих_объектов)
(Просмотр_объекта) o-- (Добавление_в_закладки)
(Просмотр_объекта) o-- (Удаление_из_закладок)
(Просмотр_списка_объектов) <|-- (Редактирование_списка_объектов)
(Редактирование_списка_объектов) o-- (Добавление_объекта)
(Редактирование_списка_объектов) o-- (Редактирование_объекта)
(Редактирование_объекта) o-- (Редактирование_данных_объекта)
(Редактирование_объекта) o-- (Загрузка_медиафайла)
(Редактирование_списка_объектов) o-- (Удаление_объекта)
(Редактирование_списка_объектов) <|-- (Просмотр_своих_объектов)

@enduml